name: "CD"

on:
  push:
    branches: [master]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25  # v1.6.0

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2  # v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: "Login to ECR"
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2  # v1.3.3

      - name: "Build, tag, cache, and push the image to ECR"
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a  # v2.10.0
        with:
          context: backend
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/apilytics-geoip-prod:${{ github.sha }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2  # v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: "Download the current task definition"
        run: >
          aws ecs describe-task-definition --task-definition apilytics-geoip-prod-task --query taskDefinition > task-definition.json

      - name: "Update tag to the task definition"
        id: update-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@374ee96751fffe528c09b5f427848da60469bb55  # v1.1.1
        with:
          task-definition: task-definition.json
          container-name: apilytics_geoip_prod
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/apilytics-geoip-prod:${{ github.sha }}

      - name: "Deploy the new task definition"
        uses: aws-actions/amazon-ecs-deploy-task-definition@9c18d81893224634ac107b91720119c91c1d600e  # v1.4.9
        with:
          task-definition: ${{ steps.update-task-def.outputs.task-definition }}
          service: apilytics-geoip-prod-service
          cluster: apilytics-geoip-prod-cluster
          wait-for-service-stability: true
